### ISSUE TITLE
Action Items - Meeting #16 (26 September)

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/working-group#33]
## ACTION ITEMS

* [ ] respond to the email thread behind datproject/security-discussion#1 (@mafintosh)
* [ ] write up some notes on spec changes for hyperdb (simplifications & single-writer) (@mafintosh)
* [x] respond to datprotocol/DEPs#40 with "soft no" (@pfrazee)
* [x] merge datprotocol/DEPs#41 (@bnewbold)
* extensions
  - [ ] add extension process note to DEP repo (@pfrazee)
* hyperdb DEP
  - [ ] get hyperdb update ready for vote (@bnewbold)
* privacy/security
  - [ ] prioritize having beaker leave a swarm when you leave the page (@pfrazee)
  - [ ] docs update (@joehand)
  - [ ] OTF red team audit application (@joehand)
  - [ ] try using dat over tor (@pfrazee)
  - [ ] benchmark over wan (if tor works, @pfrazee)
  - [ ] experiment and write up tor experiments (@bnewbold)
